targets:
  $default:
    builders:
      source_gen|combining_builder:
        generate_for:
          exclude:
            - "**/test/**"
      get_it_injector_gen:
        enabled: true
        options:
          register:
            - "Bloc$"
          ignore_for_file:
            - cs_forbidden_imports
            - directives_ordering
            - unnecessary_lambdas
            - prefer_const_constructors
            - require_trailing_commas
            - implementation_imports
            - cs_forbidden_imports
            - lines_longer_than_80_chars
            - duplicate_ignore

      bloc_enhancer_gen:
        enabled: true
        options:
          auto_enhance: true
          avoid_events:
            - Emit
            - NotifyOfError
          create_state_factory: false
          create_event_factory: false

      equatable_gen:
        enabled: true
        options:
          auto_include: true
